sudo: required
dist: trusty
language: node_js
notifications:
  email: false
node_js:
  - "8"
addons:
  chrome: stable

before_script:
  - grunt connect:test:keepalive &

script:
  - grunt build
  - npm test

